import Head from 'next/head'
import Image from 'next/image'
import { client } from '../lib/client';
import { urlFor } from '../lib/client';
import { AiOutlineStar } from 'react-icons/ai';

export default function Home({results}) {
// console.log(results)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="bg-white">
      <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
        <h2 className="sr-only">Products</h2>

        <div className="grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
          {results.map((product) => (
            <a key={product.id} href={product.slug} className="group">
              <div className="aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-w-7 xl:aspect-h-8">
                <img
                  src={urlFor(product.image && product.image[0])}
                  // alt={product.imageAlt}
                  className="h-full w-full object-cover object-center group-hover:opacity-75"
                />
              </div>
              <h3 className="mt-4 text-sm text-gray-700">{product.title}</h3>
              <p className="mt-1 text-lg font-medium text-gray-900">{product.pricePerNight}</p>
              <p className="mt-1 text-lg font-medium text-gray-900">{product.beds}</p>
              <p className="mt-1 text-lg font-medium text-gray-900">{product.bedrooms}</p>
            </a>
          ))}
        </div>
      </div>
    </div> */}

<section class="text-gray-600 body-font lg:px-48">
  <div class="container px-5 py-5 mx-auto">
    <div class="flex flex-wrap -m-4">
    {results.map((item)=>{
    return <div class="p-4 md:w-1/3">
        <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
          <img class="lg:h-48 md:h-36 w-full object-cover object-center" src={urlFor(item.image && item.image[0])} alt="blog"/>
          <div class="p-6">
            <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">{item.propertyType}</h2>
            <h1 class="title-font text-lg font-medium text-gray-900 mb-3">{item.title}</h1>
            <p class="leading-relaxed mb-3">{item.description}</p>
            <p class="leading-relaxed mb-3">Price Per Night : {item.pricePerNight}</p>
            <div class="flex items-center flex-wrap ">
              <a   href={`/product/${item.slug.current}`} class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0 cursor-pointer">Explore More
                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
              <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1  border-gray-200">
              
              <AiOutlineStar className='mr-1 w-10 h-5'/>{item.rating}
              </span>
            </div>
          </div>
        </div>
      </div>})}
    </div>
  </div>
</section>
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "properties"]';
  const results = await client.fetch(query);
  return {
    props: { results }
  }
}
